### ISSUE TITLE
Minor issues to sort out before First Release

### ISSUE THREAD

**Issue by Vikhyath08** [IIT-BHU-InstiApp/IIT-BHU-app#251]
- [x] Allow phone numbers to be entered without country code(i.e. +91 should not be necessary).(Fixed in #257 )
- [x] Make links in workshop description clickable so that forms can be floated in an easier manner.(Unnecessary)
- [x] Change the link option in resources such that "https://" is not necessary for every link.(Fixed in #258 )
- [x] (UI) Make the spacing of links(Facebook, Instagram etc.) even, even when some links are absent.(Fixed in #253 )
- [x] (UI) Make the subscriptions button more prominent(maybe by adding some text next to it).(Fixed in #256 )
- [x] Remove "Upcoming" in workshops and get the workshops sorted by date from the backend.(Fixed in #254 )
- [x] Tapping on the middle button in the outer circle of FAB works only on multiple tries to its top-left.(Fixed [here](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/commit/78114230678419b0112242200521e3a8cd9e172c))
- [x] Create event displays as "Creating Workshops".(Fixed in #255 )
- [x] Workshop not being created with location.
- [x] Adding location for event creation doesnt work. Without location, event is created with no problems.
- [x] `will pop scope` in workshop and event create screen!(Fixed [here](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/commit/59dd70fdcb7627bc2e453c72f017e7a2ef9b6eaf))
- [x] Renderflow error in Club workshop/event panel(probably same in entity as well).(Fixed in #260 )
- [x] Switch yes and no buttons in dialog popups so that affirmation is on the right and negation on the left.(Fixed in #262 )
- [x] (UI) Change text color to `ColorConstants.textColor` everywhere. (especially search in dark theme, and "no workshop" result for search in dark theme)
- [x] Make a manual for the app so that people can understand it easier.(Unnecessary)

**Comment by mohit-mangal** [comment]
@Vikhyath08 Set a global theme inside MaterialApp for text color and set that with ColorConstants.textColor.
In this way be default, text will apply that theme and we don't have to explicitly set color in every TextStyle with ColorConstants.textColor.
